/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2023-05-03 07:52:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.minihome.setting;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class settingTab2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/final/dd/Final/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1681389064750L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/final/dd/Final/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/final/dd/Final/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>미니홈피 기본 설정</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        #wrap{\r\n");
      out.write("            width: 550px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("        th{\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            background-color: lightgray;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        tr{\r\n");
      out.write("            height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        td{\r\n");
      out.write("            width: 300px;\r\n");
      out.write("        }\r\n");
      out.write("        #btnwrap{\r\n");
      out.write("            margin: 30px 70px;\r\n");
      out.write("        }\r\n");
      out.write("        table, th, td{\r\n");
      out.write("            border: 1px solid;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.3.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/GGAN.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("    <p>미니홈페이지 관리</p>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <br>\r\n");
      out.write("    <form>\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>검색 허용</th>\r\n");
      out.write("                <td>\r\n");
      out.write("                    &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                    <input type=\"radio\" id=\"yes\" name=\"radio\" value=\"Y\"><label for=\"yes\">예</label>\r\n");
      out.write("                    &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                    <input type=\"radio\" id=\"no\" name=\"radio\" value=\"N\"><label for=\"no\">아니오</label>\r\n");
      out.write("                    &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                    <input type=\"button\" onclick=\"update()\" value=\"적용\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>스킨</th>\r\n");
      out.write("                <td>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                    <select name=\"skin\" id=\"skin\">\r\n");
      out.write("                        <option selected>------선택------</option>\r\n");
      out.write("                        <option value=\"NONE\">기본 스킨</option>\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <input type=\"button\" onclick=\"Skinupdate();\" value=\"적용\">\r\n");
      out.write("                </td>                \r\n");
      out.write("            </tr>    \r\n");
      out.write("            <tr>\r\n");
      out.write("            \r\n");
      out.write("                <th>MBTI 변경하기</th>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"radio\" id=\"ISTF\" name =\"mbti\" value=\"ISTF\"><label for=\"ISTF\">ISFT</label>\r\n");
      out.write("                    <input type=\"radio\" id=\"INFJ\" name =\"mbti\" value=\"INFJ\"><label for=\"INFJ\">INFJ</label>\r\n");
      out.write("                    <input type=\"radio\" id=\"ISTP\" name =\"mbti\" value=\"ISTP\"><label for=\"ISTP\">ISTP</label>\r\n");
      out.write("                    <input type=\"radio\" id=\"ENFJ\" name =\"mbti\" value=\"ENFJ\"><label for=\"ENFJ\">ENFJ</label>\r\n");
      out.write("                    <input type=\"radio\" id=\"INTJ\" name =\"mbti\" value=\"INTJ\"><label for=\"INTJ\">INTJ</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <input type=\"button\" onclick=\"mbtiUpdate()\" value=\"적용\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>        \r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    \tvar miniNo = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${integer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    \r\n");
      out.write("    \t\r\n");
      out.write("    \tfunction update(){\r\n");
      out.write("\t\t\tvar param = {\r\n");
      out.write("\t\t\t\tsearchme: $('input[name=\"radio\"]:checked').val(),\r\n");
      out.write("\t\t\t\tminiNo\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tajaxJsonParam(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/minihome/setting/update/search\", param, function(data){\r\n");
      out.write("            \tif(data){       \t\t\r\n");
      out.write("            \t\talert(\"수정 완료\");\r\n");
      out.write("            \t}  \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    /* \tvar product_name = \"\";\r\n");
      out.write("    \t\t$('select[name=\"skin\"]').change(function(){\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\tproduct_name = $(this).val();\r\n");
      out.write("    \t\t\tconsole.log(product_name);\r\n");
      out.write("    \t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("    \t\tconsole.log(product_name); */\r\n");
      out.write("    \t\r\n");
      out.write("    \tfunction Skinupdate(){\r\n");
      out.write("    \t\tvar theme = $('#skin option:selected').val();\r\n");
      out.write("    \t\tconsole.log(theme);    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("    \t\t\ttype: 'put',\r\n");
      out.write("    \t\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/minihome/setting/update/skin',\r\n");
      out.write("    \t\t\theaders : {\r\n");
      out.write("    \t\t\t\t'Content-Type' : 'application/json',\r\n");
      out.write("\t                 'X-HTTP-Method-Override' : 'PUT'\r\n");
      out.write("    \t\t\t},\r\n");
      out.write("    \t\t\tdata: JSON.stringify({\r\n");
      out.write("    \t\t\t\t'theme' : theme\r\n");
      out.write("    \t\t\t}),\r\n");
      out.write("    \t\t\tsuccess : function(result){\r\n");
      out.write("    \t\t\t\tif(result == 1){\r\n");
      out.write("    \t\t\t\t\talert('수정 성공');\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\twindow.parent.location.reload();\t\t\t\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\t\r\n");
      out.write("\t\tfunction mbtiUpdate(){\r\n");
      out.write("\t\t\tvar param = {\r\n");
      out.write("\t\t\t\tmbti: $('input[name=\"mbti\"]:checked').val(),\r\n");
      out.write("\t\t\t\tminiNo\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tajaxJsonParam(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/minihome/setting/update/mbti\", param, function(data){\r\n");
      out.write("            \tif(data){       \t\t\r\n");
      out.write("            \t\talert(\"수정 완료\");\r\n");
      out.write("            \t\twindow.parent.location.reload();\r\n");
      out.write("            \t}  \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/minihome/setting/settingTab2.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/minihome/setting/settingTab2.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/minihome/setting/settingTab2.jsp(7,0) '${ pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/minihome/setting/settingTab2.jsp(64,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("skinList");
      // /WEB-INF/views/minihome/setting/settingTab2.jsp(64,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/minihome/setting/settingTab2.jsp(64,24) '${skinList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${skinList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                        \t<option id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${skinList.product_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${skinList.product_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${skinList.product_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
