/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2023-04-26 10:56:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.webpage.ilchon;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class readModal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/final/dd/Final/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1681389064750L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/final/dd/Final/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/final/dd/Final/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>일촌 신청 팝업</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t*{\r\n");
      out.write("\t  margin:0;\r\n");
      out.write("\t  padding:0;\r\n");
      out.write("\t  box-sizing: border-box;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tp{\r\n");
      out.write("\t  margin-top:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-btn-box{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  text-align:center;\r\n");
      out.write("\t  margin-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-btn-box button{\r\n");
      out.write("\t  display:inline-block;\r\n");
      out.write("\t  width:100px;\r\n");
      out.write("\t  height:30px;\r\n");
      out.write("\t  background-color:#ffffff;\r\n");
      out.write("\t  border:1px solid #e1e1e1;\r\n");
      out.write("\t  cursor:pointer;\r\n");
      out.write("\t  padding:1px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.popup{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  max-width:400px;\r\n");
      out.write("\t  background-color:#ffffff;\r\n");
      out.write("\t  border-radius:10px;\r\n");
      out.write("\t  overflow:hidden;\r\n");
      out.write("\t  background-color:rgb(243, 156, 18);\r\n");
      out.write("\t  box-shadow: 5px 10px 10px 1px rgba(0,0,0,.3);\r\n");
      out.write("\t}\r\n");
      out.write("\t.popup-head{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  height:50px;\r\n");
      out.write("\t  display:flex;\r\n");
      out.write("\t  align-items:center;\r\n");
      out.write("\t  justify-content:center;\r\n");
      out.write("\t    padding:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.head-title {\r\n");
      out.write("\t    font-size: 20px;\r\n");
      out.write("\t    font-style: italic;\r\n");
      out.write("\t    font-weight: 700;\r\n");
      out.write("\t    letter-spacing: -3px;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.popup-body{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  background-color:#ffffff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.body-content{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  padding:30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.body-titlebox{\r\n");
      out.write("\t  text-align:center;\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  height:40px;\r\n");
      out.write("\t  margin-bottom:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.body-contentbox{\r\n");
      out.write("\t  border:0.5px solid #ddd;\r\n");
      out.write("\t  word-break:break-word;\r\n");
      out.write("\t  overflow-y:auto;\r\n");
      out.write("\t  min-height:100px;\r\n");
      out.write("\t  max-height:300px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.popup-foot{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  height:50px;\r\n");
      out.write("\t  background-color:rgb(243, 156, 18);\r\n");
      out.write("\t}\r\n");
      out.write("\t.pop-btn{\r\n");
      out.write("\t  display:inline-flex;\r\n");
      out.write("\t  width:50%;\r\n");
      out.write("\t  height:100%;\r\n");
      out.write("\t  float:left;\r\n");
      out.write("\t  justify-content:center;\r\n");
      out.write("\t  align-items:center;\r\n");
      out.write("\t  color:#ffffff;\r\n");
      out.write("\t  cursor:pointer;\r\n");
      out.write("\t  background-color:rgb(243, 156, 18);\r\n");
      out.write("\t  border:0.5px solid #ddd;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pop-btn.confirm{\r\n");
      out.write("\t  order-right:1px solid rgb(243, 156, 18);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.modal-btn-box input{\r\n");
      out.write("\t  display:inline-block;\r\n");
      out.write("\t  width:100px;\r\n");
      out.write("\t  height:30px;\r\n");
      out.write("\t  background-color:#ffffff;\r\n");
      out.write("\t  border:1px solid #e1e1e1;\r\n");
      out.write("\t  cursor:pointer;\r\n");
      out.write("\t  padding:1px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.popup-wrap{\r\n");
      out.write("\t  width:400px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.popup-wrap{\r\n");
      out.write("\t  justify-content:center;\r\n");
      out.write("\t  align-items:center;\r\n");
      out.write("\t  position:fixed;\r\n");
      out.write("\t  top:0;\r\n");
      out.write("\t  left:0;\r\n");
      out.write("\t  right:0;\r\n");
      out.write("\t  bottom:0;        \r\n");
      out.write("\t }\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 신청 팝업 -->\r\n");
      out.write("<div class=\"popup-wrap\">\r\n");
      out.write("\t<div id=\"requestIlchon-container\">\r\n");
      out.write("\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/webpage/ilchon/readModal\" method=\"POST\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"requestNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ request.requestNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"sender\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ request.sender }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"receiver\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ request.receiver }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<div class=\"popup\">\r\n");
      out.write("\t\t    <div class=\"popup-head\">\r\n");
      out.write("\t\t        <span class=\"head-title\"><h2>일촌 신청 해요!</h2></span>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <div class=\"popup-body\">\r\n");
      out.write("\t\t\t\t<div class=\"body-content\">\r\n");
      out.write("\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t<label for=\"sender\">\r\n");
      out.write("\t\t\t\t\t<h3>From.</label>\r\n");
      out.write("\t\t\t\t    \t<input type=\"text\" name=\"sender\" id=\"sender\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.sender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:255px; min-height:30px; border:0px #ddd; background-color:white;\" disabled/>\r\n");
      out.write("\t\t\t\t    </h3>\r\n");
      out.write("\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t    <label for=\"requestTitle\">친구가 정한 일촌명</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" name=\"ilchonNick\" id=\"ilchonNick\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.ilchonNick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:340px; min-height:30px; border:0.5px solid #ddd;\" disabled/>\r\n");
      out.write("\t\t\t\t   \t<br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t    <label for=\"requestTitle\">신청 제목</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" name=\"requestTitle\" id=\"requestTitle\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.requestTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:340px; min-height:30px; border:0.5px solid #ddd;\" placeholder=\"제목을 입력하세요.\" disabled/>\r\n");
      out.write("\t\t\t\t   \t<br><br>\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t    <label for=\"requestContent\">신청 내용</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" name=\"requestContent\" id=\"messageContent\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.requestContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"body-contentbox\" style=\"width:340px; min-height:100px; resize: none; border:0.5px solid #ddd;\" maxlength=\"200\" name=\"content\" id=\"replyContent\" placeholder=\"신청 내용을 입력하세요.\" disabled>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"popup-foot\">\r\n");
      out.write("\t\t     \t<input id=\"close\" class=\"pop-btn close\" type=\"button\" value=\"닫기\" onclick=\"self.close();\">\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/webpage/ilchon/readModal.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/webpage/ilchon/readModal.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/webpage/ilchon/readModal.jsp(7,0) '${ pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
