/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2023-04-26 10:55:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.webpage.ilchon;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class requestBox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/final/dd/Final/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1681389064750L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/final/dd/Final/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/final/dd/Final/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\" integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.3.js\"></script>\r\n");
      out.write("    <title>일촌 리스트</title>\r\n");
      out.write("    \r\n");
      out.write("    <style>        \r\n");
      out.write("        div,ul,li{margin:0; padding:0;}\r\n");
      out.write("        ul,li {list-style:none;}\r\n");
      out.write("        .tab{float:left; width:1100px; height:290px;}\r\n");
      out.write("        .tabnav{font-size:0; width:1100px; border:1px solid #ddd;}\r\n");
      out.write("        .tabnav li{display: inline-block;  height:46px; text-align:center; border-right:1px solid #ddd;}\r\n");
      out.write("        .tabnav li a:before{content:\"\"; position:absolute; left:0; top:0px; width:100%; height:3px; }\r\n");
      out.write("        .tabnav li a.active:before{background:rgb(243, 156, 18);}\r\n");
      out.write("        .tabnav li a.active{border-bottom:1px solid #fff;}\r\n");
      out.write("        .tabnav li a{ position:relative; display:block; background: #f8f8f8; color: #000; padding:0 30px; line-height:46px; text-decoration:none; font-size:16px;}\r\n");
      out.write("        .tabnav li a:hover,\r\n");
      out.write("        .tabnav li a.active{background:#fff; color:rgb(243, 156, 18); }\r\n");
      out.write("        .tabcontent{padding: 20px; border:1px solid #ddd; border-top:none;}\r\n");
      out.write("        .searchContent{width: 1000px; padding: 0px; border:1px solid #ddd; margin-left: auto; margin-right: auto;}\r\n");
      out.write("\r\n");
      out.write("        /* skin */\r\n");
      out.write("        .ilchon-list{\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        margin-left: auto;\r\n");
      out.write("        margin-right: auto;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ilchons h3{\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        color: #545454;\r\n");
      out.write("        margin-top:60px;\r\n");
      out.write("        margin-bottom: 60px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .ilchon{\r\n");
      out.write("        display: block;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        text-decoration:none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        float:left;\r\n");
      out.write("        margin-left: 30px;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .ilchon-name{\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        margin-bottom: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .ilchon-nick{\r\n");
      out.write("        color: #545454;\r\n");
      out.write("        font-size: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .clearfix{\r\n");
      out.write("        clear: both;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 서치 영역 */\r\n");
      out.write("        .searchList{\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        margin-left: auto;\r\n");
      out.write("        margin-right: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-box {\r\n");
      out.write("    \twidth: 400px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("    .search-btn {\r\n");
      out.write("        color: #EDEDED;\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        background: rgb(243, 156, 18);\r\n");
      out.write("        /* display: flex; */\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("        \r\n");
      out.write("     /* 팝업 스타일 */\r\n");
      out.write("\t*{\r\n");
      out.write("\t  margin:0;\r\n");
      out.write("\t  padding:0;\r\n");
      out.write("\t  box-sizing: border-box;\r\n");
      out.write("\t}\r\n");
      out.write("\tp{\r\n");
      out.write("\t  margin-top:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-btn-box{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  text-align:center;\r\n");
      out.write("\t  margin-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-btn-box button{\r\n");
      out.write("\t  display:inline-block;\r\n");
      out.write("\t  width:100px;\r\n");
      out.write("\t  height:30px;\r\n");
      out.write("\t  background-color:#ffffff;\r\n");
      out.write("\t  border:1px solid #e1e1e1;\r\n");
      out.write("\t  cursor:pointer;\r\n");
      out.write("\t  padding:1px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.popup-wrap{\r\n");
      out.write("\t  background-color:rgba(0,0,0,.3);\r\n");
      out.write("\t  justify-content:center;\r\n");
      out.write("\t  align-items:center;\r\n");
      out.write("\t  position:fixed;\r\n");
      out.write("\t  top:0;\r\n");
      out.write("\t  left:0;\r\n");
      out.write("\t  right:0;\r\n");
      out.write("\t  bottom:0;\r\n");
      out.write("\t  display:none;\r\n");
      out.write("\t  padding:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.popup{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  max-width:400px;\r\n");
      out.write("\t  background-color:#ffffff;\r\n");
      out.write("\t  border-radius:10px;\r\n");
      out.write("\t  overflow:hidden;\r\n");
      out.write("\t  background-color:rgb(243, 156, 18);\r\n");
      out.write("\t  box-shadow: 5px 10px 10px 1px rgba(0,0,0,.3);\r\n");
      out.write("\t}\r\n");
      out.write("\t.popup-head{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  height:50px;\r\n");
      out.write("\t  display:flex;\r\n");
      out.write("\t  align-items:center;\r\n");
      out.write("\t  justify-content:center;\r\n");
      out.write("\t    padding:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.head-title {\r\n");
      out.write("\t    font-size: 20px;\r\n");
      out.write("\t    font-style: italic;\r\n");
      out.write("\t    font-weight: 700;\r\n");
      out.write("\t    letter-spacing: -3px;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.popup-body{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  background-color:#ffffff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.body-content{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  padding:30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.body-titlebox{\r\n");
      out.write("\t  text-align:center;\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  height:40px;\r\n");
      out.write("\t  margin-bottom:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.body-contentbox{\r\n");
      out.write("\t  border:0.5px solid #ddd;\r\n");
      out.write("\t  word-break:break-word;\r\n");
      out.write("\t  overflow-y:auto;\r\n");
      out.write("\t  min-height:100px;\r\n");
      out.write("\t  max-height:400px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.popup-foot{\r\n");
      out.write("\t  width:100%;\r\n");
      out.write("\t  height:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pop-btn{\r\n");
      out.write("\t  display:inline-flex;\r\n");
      out.write("\t  width:33%;\r\n");
      out.write("\t  height:100%;\r\n");
      out.write("\t  float:left;\r\n");
      out.write("\t  justify-content:center;\r\n");
      out.write("\t  align-items:center;\r\n");
      out.write("\t  color:#ffffff;\r\n");
      out.write("\t  cursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pop-btn.confirm{\r\n");
      out.write("\t  order-right:1px solid rgb(243, 156, 18);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("    </style>\r\n");
      out.write("    \t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<h2>일촌 신청함</h2>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<hr>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"tab\">\r\n");
      out.write("        <ul class=\"tabnav\">\r\n");
      out.write("            <li><a href=\"#toRequest\">보낸 신청함</a></li>\r\n");
      out.write("            <li><a href=\"#fromRequest\">받은 신청함</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("            \r\n");
      out.write("        <div class=\"tabcontent\">\r\n");
      out.write("                <!-- 보낸 신청함 리스트 -->\r\n");
      out.write("\t\t\t<div id=\"toRequest\">\r\n");
      out.write("                    <div class=\"ilchons\">\r\n");
      out.write("                        <div class=\"ilchon-list\">\r\n");
      out.write("                            <a href=\"#\" class=\"ilchon\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/pompom.png\" width=\"200px\">\r\n");
      out.write("                                <div class=\"ilchon-name\">\r\n");
      out.write("                                    아이디\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"ilchon-nick\">\r\n");
      out.write("                                    일촌명\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }/webpage/ilchon/inbox", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"clearfix\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 일촌 신청 보관함 -->\r\n");
      out.write("                <div id=\"fromRequest\">\r\n");
      out.write("                    <div class=\"ilchons\">\r\n");
      out.write("                        <div class=\"ilchon-list\">\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("                      \t\t\r\n");
      out.write("\t                        <!-- 일촌 신청 정보 -->\r\n");
      out.write("\t                        <div class=\"container\">\r\n");
      out.write("\t                            <a href=\"#\" class=\"ilchon\">\r\n");
      out.write("\t                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/pompom.png\" width=\"200px\">\r\n");
      out.write("\t                                <div class=\"ilchon-name\">\r\n");
      out.write("\t                                    아이디\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                <div class=\"ilchon-nick\">\r\n");
      out.write("\t                                    일촌명\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                ");
      out.write("\r\n");
      out.write("\t                            \t<button type=\"button\" id=\"modal-open\" onclick=\"javascrit:window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/webpage/ilchon/requestModal','popup_1','width=500px,height=400px,toolbar=no,location=no,status=no,menubar=no,scrollbars=no,resizable=no,left=300px,top=100px')\">\r\n");
      out.write("\t                            \t신청 내용 확인 </button>\r\n");
      out.write("\t                            </a>\r\n");
      out.write("\t                         </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div> \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function(){\r\n");
      out.write("            $('.tabcontent > div').hide();\r\n");
      out.write("            $('.tabnav a').click(function () {\r\n");
      out.write("                $('.tabcontent > div').hide().filter(this.hash).fadeIn();\r\n");
      out.write("                $('.tabnav a').removeClass('active');\r\n");
      out.write("                $(this).addClass('active');\r\n");
      out.write("                return false;\r\n");
      out.write("            }).filter(':eq(0)').click();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t  $(\"#confirm\").click(function(){\r\n");
      out.write("\t\t      modalClose(); //모달 닫기 함수 호출\r\n");
      out.write("\t\t      //컨펌 이벤트 처리 (나의 일촌으로 변경)\r\n");
      out.write("\t\t      Success();\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t  $(\"#cancle\").click(function(){\r\n");
      out.write("\t\t      modalClose(); //모달 닫기 함수 호출\r\n");
      out.write("\t\t      //취소 이벤트 처리\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t  $(\"#modal-open\").click(function(){        \r\n");
      out.write("\t\t      $(\"#popup\").css('display','flex').hide().fadeIn();\r\n");
      out.write("\t\t      //팝업을 flex속성으로 바꿔준 후 hide()로 숨기고 다시 fadeIn()으로 효과\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t  $(\"#close\").click(function(){\r\n");
      out.write("\t\t      modalClose(); //모달 닫기 함수 호출\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  function modalClose(){\r\n");
      out.write("\t\t      $(\"#popup\").fadeOut(); //페이드아웃 효과\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  function Success(){\r\n");
      out.write("\t\t      $(\"#modal-open\").css('background-color','rgb(243, 156, 18)');\r\n");
      out.write("\t\t      $('#modal-open').html('<div class=\"icon-ok\"></div> 나의 일촌');\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t});\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/webpage/ilchon/requestBox.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/webpage/ilchon/requestBox.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/webpage/ilchon/requestBox.jsp(7,0) '${ pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/webpage/ilchon/requestBox.jsp(251,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty list }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <p>일촌 신청 목록이 없습니다.</p>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
